Repository zadjii-msft/PowerToys, pull requests merged in 2025-01, with the labels that each got.

#269 Introduce an `Id` property for command providers
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Apps/AllAppsCommandProvider.cs
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Bookmark/BookmarksCommandProvider.cs
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Calc/CalculatorCommandProvider.cs
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.CmdPalSettings/SettingsCommandProvider.cs
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Registry/RegistryCommandsProvider.cs
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Shell/ShellCommandsProvider.cs
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowWalker/WindowWalkerCommandsProvider.cs
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowsServices/WindowsServicesCommandsProvider.cs
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowsSettings/WindowsSettingsCommandsProvider.cs
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowsTerminal/WindowsTerminalCommandsProvider.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Commands/BuiltInsCommandProvider.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Commands/ReloadExtensionsCommandProvider.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Messages/QuitMessage.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI/App.xaml.cs
  src/modules/cmdpal/doc/initial-sdk-spec/initial-sdk-spec.md
  src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/CommandProvider.cs
  src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions/Microsoft.CmdPal.Extensions.idl
Labels: Area-API

#282 Allow CommandProviders to ItemsChanged themselves
  src/modules/cmdpal/doc/initial-sdk-spec/initial-sdk-spec.md
  src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/CommandProvider.cs
  src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions/Microsoft.CmdPal.Extensions.idl
Labels: Area-API

#287 Indexer pagination
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Indexer/Pages/IndexerPage.cs
  src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.Indexer/Indexer/SearchQuery.cs
Labels: Wanted for selfhost

#209 Add WebSearch Plugin from PT Run
  PowerToys.sln
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WebSearch/Helpers/HistoryItem.cs
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WebSearch/Helpers/SettingsManager.cs
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WebSearch/Microsoft.CmdPal.Ext.WebSearch.csproj
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WebSearch/Pages/SettingsPage.cs
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WebSearch/Pages/WebSearchListPage.cs
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WebSearch/Properties/Resources.Designer.cs
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WebSearch/Properties/Resources.resx
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WebSearch/WebSearchCommandsProvider.cs
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WebSearch/WebSearchTopLevelCommandItem.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI/App.xaml.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI/Microsoft.CmdPal.UI.csproj
  src/modules/cmdpal/WindowsCommandPalette/Microsoft.CmdPal.UI.Poc.csproj
  src/modules/cmdpal/WindowsCommandPalette/Views/MainViewModel.xaml.cs
  src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WebSearch/Commands/SearchWebCommand.cs
  src/modules/cmdpal/exts/Microsoft.CmdPal.Ext.WebSearch/FallbackExecuteSearchItem.cs
Labels: Wanted for selfhost

#291 Fix the namespaces for the pilfered KB control
  src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/KeyVisual/KeyVisual.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/KeyVisual/KeyVisual.xaml
  src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/ShortcutControl/ShortcutControl.xaml
  src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/ShortcutControl/ShortcutControl.xaml.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/ShortcutControl/ShortcutDialogContentControl.xaml
  src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/ShortcutControl/ShortcutDialogContentControl.xaml.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/ShortcutControl/ShortcutWithTextLabelControl.xaml
  src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/ShortcutControl/ShortcutWithTextLabelControl.xaml.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI/SettingsPage.xaml
Labels: Area-Code Health, Wanted for selfhost

#265 Add some padding for font icons
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.WindowsServices/Helpers/ServiceHelper.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/IconBox.cs
Labels: Wanted for selfhost

#293 When an extension item fails to load, replace it with an error item
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandItemViewModel.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ListViewModel.cs
Labels: Wanted for selfhost

#290 Fix `Loading` on pages
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/LoadingPageViewModel.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/PageViewModel.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/SettingsViewModel.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ShellViewModel.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI/ShellPage.xaml
Labels: Wanted for selfhost

#294 Spec `GoToPageArgs.NavigationMode`
  src/modules/cmdpal/doc/initial-sdk-spec/initial-sdk-spec.md
  src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions.Helpers/GoToPageArgs.cs
  src/modules/cmdpal/extensionsdk/Microsoft.CmdPal.Extensions/Microsoft.CmdPal.Extensions.idl
Labels: Area-API, Wanted for selfhost

#289 Implement Allowing CommandProviders to ItemsChanged themselves
  src/modules/cmdpal/Exts/Microsoft.CmdPal.Ext.Bookmark/BookmarksCommandProvider.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/CommandProviderWrapper.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TopLevelCommandManager.cs
Labels: Wanted for selfhost

#295 Add `??` alias to TRA for web search plugin
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/AliasManager.cs
Labels: Wanted for selfhost

#241 Fix the reload extensions command item
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Commands/BuiltInsCommandProvider.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Commands/FallbackReloadItem.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Commands/MainListPage.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Commands/ReloadExtensionsAction.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ListViewModel.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/Messages/ReloadCommandsMessage.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/ShellViewModel.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TopLevelCommandManager.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI.ViewModels/TopLevelCommandWrapper.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI/Controls/SearchBar.xaml.cs
  src/modules/cmdpal/Microsoft.CmdPal.UI/MainWindow.xaml
Labels: Wanted for selfhost
